backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: date, label: Publish date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
