display_url: https://rockxxl.com
logo_url: /logo-black.svg

backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor

media_folder: static/assets
media_library:
  name: cloudinary
  config:
    cloud_name: rockxxl
    api_key: 953577883219134
    output_filename_only: true
public_folder: assets

editor:
  preview: false

collections:
  - name: category
    label: Categories
    label_singular: Category
    folder: src/pages/category
    create: true
    delete: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown, required: false }

  - name: author
    label: Authors
    label_singular: Author
    folder: src/pages/author
    create: true
    delete: true
    fields:
      - { name: title, label: Title }
      - { name: email, label: Email, required: false }
      - { name: avatar, label: Avatar, widget: image, media_library: { output_filename_only: true }, required: false}
      - { name: body, label: Body, widget: markdown, required: false }

  - name: post
    label: Posts
    label_singular: Post
    folder: src/pages/post
    create: true
    delete: true
    filter:
      - field: category
        value: Nieuws
    fields:
      - name: title
        label: Title
      - name: thumbnail
        label: Featured Image
        widget: image
        media_library: { output_filename_only: true }
      - name: date
        label: Publish date
        widget: datetime
      - name: eventdate
        label: Date event
        widget: datetime
      - name: category
        label: Category
        widget: relation
        collection: category
        searchFields: ["title"]
        valueField: title
      - name: author
        label: Author
        widget: relation
        collection: author
        searchFields: ["title"]
        valueField: title
        displayFields: title
      # - label: Bands
      #   name: groups
      #   widget: "list"
      #   default: [""]
      #   required: false
      - label: Album
        name: album
        required: false
      - name: externalUrl
        label: Externe URL
        hint: Link the list-item to an external website. eg. Facebook event-page.
      - name: body
        label: Body
        widget: markdown
      - name: permalink
        label: Legacy URL
        widget: hidden
        required: false
