backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor

media_folder: static/assets
media_library:
  name: cloudinary
  config:
    cloud_name: rockxxl
    api_key: 953577883219134
    output_filename_only: true
public_folder: assets

collections:
  - name: category
    label: Category
    folder: src/pages/category
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: post
    label: Post
    folder: src/pages/post
    create: true
    fields:
      - name: title
        label: Title
      - name: thumbnail
        label: Featured Image
        widget: image
        media_library: { output_filename_only: true }
      - name: date
        label: Publish date
        widget: datetime
        format: "D MMM YYY, HH:mm"
      - name: category
        label: Category
        widget: relation
        collection: category
        searchFields: ["title"]
        valueField: title
        displayFields: title
      - name: body
        label: Body
        widget: markdown
